"""Project MANIFOLD simulation package."""

from .simulation import (
    GenerationSummary,
    LifeResult,
    ManifoldExperiment,
    SimulationConfig,
    VectorGenome,
    run_experiment,
    transfer_population,
)
from .trustrouter import (
    DialogueTask,
    TrustLearningMemory,
    TrustRouter,
    TrustRouterConfig,
    TrustRouterDecision,
    route_task,
)
from .live import GossipBus, HierarchicalLiveBrain, LiveBrain
from .encoder import (
    DualPathEncoder,
    EncoderCorrection,
    PromptCluster,
    PromptEncoder,
    PromptFeatures,
    SemanticBridge,
)
from .transfer import ReputationRegistry, WarmStartConfig, warm_start_memory
from .connector import (
    ConnectorRegistry,
    ShadowModeWrapper,
    ToolConnector,
    ToolConnectorResult,
    VirtualRegret,
)
from .hitl import (
    HITLConfig,
    HITLGate,
    HITLRecord,
    TeacherSpike,
)
from .federation import (
    FederatedGossipBridge,
    FederatedGossipPacket,
    GlobalReputationLedger,
    OrgReputationSnapshot,
    cold_start_from_ledger,
)
from .adversarial import (
    AdversarialPricingDetector,
    AuditTrigger,
    NashEquilibriumGate,
    ReputationLaunderingDetector,
    ToolOutcomeWindow,
)
from .interceptor import (
    ActiveInterceptor,
    InterceptorConfig,
    InterceptorVeto,
    InterceptResult,
    shield,
)
from .autodiscovery import (
    AutoRuleDiscovery,
    DecompositionTemplate,
    PenaltyOptimizer,
    PenaltyProposal,
    PolicySynthesizer,
    RuleObservation,
)
from .brain import (
    AssetAdapter,
    BrainConfig,
    BrainDecision,
    BrainMemory,
    BrainOutcome,
    BrainTask,
    DecompositionPlan,
    GossipNote,
    HierarchicalBrain,
    HierarchicalDecision,
    LearnedPrices,
    ManifoldBrain,
    PriceAdapter,
    ScoutRecord,
    SubTaskSpec,
    ToolProfile,
    attribute_to_tool,
    classify_user_signal,
    decide_task,
    default_tools,
)
from .brainbench import (
    BrainBenchmarkReport,
    BrainLabelledTask,
    BrainPolicyScore,
    load_brain_tasks_csv,
    run_brain_benchmark,
    sample_brain_tasks,
)
from .trustaudit import (
    TrustAuditConfig,
    TrustAuditFinding,
    TrustAuditReport,
    format_trust_audit_report,
    run_support_trust_audit,
    sample_support_tasks,
)
from .research import (
    ResearchFinding,
    ResearchReport,
    run_asset_learning_suite,
    run_dual_encoder_suite,
    run_encoder_suite,
    run_gossip_hierarchical_suite,
    run_gossip_research_suite,
    run_hierarchical_suite,
    run_price_learning_suite,
    run_research_suite,
    run_server_telemetry_suite,
    run_warm_start_suite,
)
from .trustbench import (
    BenchmarkReport,
    LabelledTask,
    PolicyScore,
    load_labelled_tasks_csv,
    run_trust_benchmark,
    sample_trust_tasks,
)
from .gridmapper import (
    AgentPopulation,
    DynamicTarget,
    GridOptimizationResult,
    GridWorld,
    Rule,
)
from .social import (
    CellVector,
    PolicyAudit,
    SocialConfig,
    SocialGenerationSummary,
    SocialGenome,
    SocialManifoldExperiment,
    compile_policy_audit,
    config_for_preset,
    recommended_prices,
    run_social_experiment,
)
from .adapters import (
    ManifoldCallbackHandler,
    ManifoldOpenAIWrapper,
)
from .hub import (
    CommunityBaseline,
    ReputationHub,
)
from .recruiter import (
    MarketplaceListing,
    RecruitmentResult,
    SovereignRecruiter,
)
from .policy import (
    DOMAIN_TEMPLATES,
    ManifoldPolicy,
    PolicyDomain,
    PolicyExporter,
    PolicyLoader,
    RuleDiff,
)
from .gitops import (
    CIRiskDelta,
    CIRiskReport,
    ManifoldCICheck,
    AutonomousPRProposal,
    PRDraft,
    generate_github_action,
)
from .b2b import (
    AgentEconomyLedger,
    B2BRouteResult,
    B2BRouter,
    EconomyEntry,
    HandshakeResult,
    OrgPolicy,
    PolicyHandshake,
)
from .crypto import (
    GossipSigner,
    OrgPolicySigner,
    PolicySigningKey,
    SignatureVerificationError,
    SignedGossipNote,
    SignedOrgPolicy,
    VerifiedPolicyHandshake,
)
from .fleet import (
    B2BEconomySnapshot,
    CIBuildHistory,
    CIBuildRecord,
    FleetDashboardData,
    FleetPanelRenderer,
)
from .polyglot import (
    ManifoldOpenAPISpec,
    generate_openapi_spec,
    spec_to_json,
    spec_to_yaml,
)
from .privacy import PrivacyConfig, PrivacyGuard
from .replay import ReplayReport, StateRehydrator, VirtualExecution
from .verify import PolicyConflict, PolicyVerifier, VerificationResult

__all__ = [
    "ActiveInterceptor",
    "AdversarialPricingDetector",
    "AuditTrigger",
    "AutoRuleDiscovery",
    "AgentPopulation",
    "AssetAdapter",
    "BrainBenchmarkReport",
    "BrainConfig",
    "BrainDecision",
    "BrainLabelledTask",
    "BrainMemory",
    "ConnectorRegistry",
    "BrainOutcome",
    "BrainPolicyScore",
    "BrainTask",
    "BenchmarkReport",
    "CellVector",
    "CommunityBaseline",
    "DecompositionTemplate",
    "DecompositionPlan",
    "DialogueTask",
    "DualPathEncoder",
    "DynamicTarget",
    "EncoderCorrection",
    "FederatedGossipBridge",
    "FederatedGossipPacket",
    "GenerationSummary",
    "GlobalReputationLedger",
    "GossipBus",
    "GossipNote",
    "GridOptimizationResult",
    "GridWorld",
    "InterceptorConfig",
    "InterceptorVeto",
    "InterceptResult",
    "HITLConfig",
    "HITLGate",
    "HITLRecord",
    "HierarchicalBrain",
    "HierarchicalDecision",
    "HierarchicalLiveBrain",
    "LearnedPrices",
    "LifeResult",
    "LiveBrain",
    "ManifoldBrain",
    "ManifoldCallbackHandler",
    "ManifoldExperiment",
    "ManifoldOpenAIWrapper",
    "NashEquilibriumGate",
    "OrgReputationSnapshot",
    "PenaltyOptimizer",
    "PenaltyProposal",
    "PolicyAudit",
    "PolicyScore",
    "PolicySynthesizer",
    "PriceAdapter",
    "PromptCluster",
    "PromptEncoder",
    "PromptFeatures",
    "ReputationHub",
    "ReputationLaunderingDetector",
    "ReputationRegistry",
    "Rule",
    "RuleObservation",
    "ResearchFinding",
    "ResearchReport",
    "ScoutRecord",
    "SemanticBridge",
    "ShadowModeWrapper",
    "TeacherSpike",
    "ToolConnector",
    "ToolConnectorResult",
    "ToolOutcomeWindow",
    "VirtualRegret",
    "SimulationConfig",
    "SocialConfig",
    "SocialGenerationSummary",
    "SocialGenome",
    "SocialManifoldExperiment",
    "SubTaskSpec",
    "TrustLearningMemory",
    "TrustAuditConfig",
    "TrustAuditFinding",
    "TrustAuditReport",
    "TrustRouter",
    "TrustRouterConfig",
    "TrustRouterDecision",
    "ToolProfile",
    "VectorGenome",
    "WarmStartConfig",
    "attribute_to_tool",
    "classify_user_signal",
    "cold_start_from_ledger",
    "compile_policy_audit",
    "config_for_preset",
    "decide_task",
    "default_tools",
    "DOMAIN_TEMPLATES",
    "format_trust_audit_report",
    "LabelledTask",
    "load_brain_tasks_csv",
    "load_labelled_tasks_csv",
    "ManifoldPolicy",
    "MarketplaceListing",
    "PolicyDomain",
    "PolicyExporter",
    "PolicyLoader",
    "RecruitmentResult",
    "recommended_prices",
    "route_task",
    "RuleDiff",
    "run_asset_learning_suite",
    "run_dual_encoder_suite",
    "run_encoder_suite",
    "run_experiment",
    "run_gossip_hierarchical_suite",
    "run_hierarchical_suite",
    "run_server_telemetry_suite",
    "run_social_experiment",
    "run_brain_benchmark",
    "run_trust_benchmark",
    "run_support_trust_audit",
    "run_gossip_research_suite",
    "run_price_learning_suite",
    "run_research_suite",
    "run_warm_start_suite",
    "sample_brain_tasks",
    "sample_support_tasks",
    "sample_trust_tasks",
    "shield",
    "SovereignRecruiter",
    "transfer_population",
    "warm_start_memory",
    # Phase 19 — GitOps Loop
    "CIRiskDelta",
    "CIRiskReport",
    "ManifoldCICheck",
    "AutonomousPRProposal",
    "PRDraft",
    "generate_github_action",
    # Phase 20 — B2B Routing
    "AgentEconomyLedger",
    "B2BRouteResult",
    "B2BRouter",
    "EconomyEntry",
    "HandshakeResult",
    "OrgPolicy",
    "PolicyHandshake",
    # Phase 21 — Zero-Trust Cryptography
    "GossipSigner",
    "OrgPolicySigner",
    "PolicySigningKey",
    "SignatureVerificationError",
    "SignedGossipNote",
    "SignedOrgPolicy",
    "VerifiedPolicyHandshake",
    # Phase 22 — Fleet Dashboard
    "B2BEconomySnapshot",
    "CIBuildHistory",
    "CIBuildRecord",
    "FleetDashboardData",
    "FleetPanelRenderer",
    # Phase 23 — Polyglot Protocol
    "ManifoldOpenAPISpec",
    "generate_openapi_spec",
    "spec_to_json",
    "spec_to_yaml",
    # Phase 35 — Privacy Guard
    "PrivacyConfig",
    "PrivacyGuard",
    # Phase 36 — Time-Travel Replay
    "ReplayReport",
    "StateRehydrator",
    "VirtualExecution",
    # Phase 37 — Formal Policy Verification
    "PolicyConflict",
    "PolicyVerifier",
    "VerificationResult",
]
